env:
  browser: true
  es2021: true
extends: eslint:recommended
parserOptions:
  ecmaVersion: latest
rules: {}
globals: {
  'GM_getValue': 'readonly',
  'GM_setValue': 'readonly',
  'GM_deleteValue': 'readonly',
  'GM_openInTab': 'readonly',
  'GM_addStyle': 'readonly'
}
